export default class Colors {

  static transparent = Color.Transparent

  static white = '#ffffffff'
  static black = $r('sys.color.black')
  static gray = Color.Gray

  static blue100 = $r('app.color.blue_100')
  static blue300 = $r('app.color.blue_300')
  static blue400 = $r('app.color.blue_400')
  static blue600 = $r('app.color.blue_600')
  static blue700 = $r('app.color.blue_700')
  static blue800 = $r('app.color.blue_800')
  static blue900 = $r('app.color.blue_900')

  static gray100 = $r('app.color.gray_100')
  static gray200 = $r('app.color.gray_200')
  static gray300 = $r('app.color.gray_300')
  static gray400 = $r('app.color.gray_400')
  static gray500 = $r('app.color.gray_500')
  static gray600 = $r('app.color.gray_600')
  static gray800 = $r('app.color.gray_800')
  static gray900 = $r('app.color.gray_900')
  static gray1000 = $r('app.color.gray_1000')

  static wraning300 = $r('app.color.wraning_300')
  static wraning400 = $r('app.color.wraning_400')
  static wraning600 = $r('app.color.wraning_600')

  static success300 = $r('app.color.success_300')
  static success500 = $r('app.color.success_500')
  static success600 = $r('app.color.success_600')
  static success700 = $r('app.color.success_700')

  static title_text_color = '#182431'
  static line_color = '#0D182431'
  static login_tips_text_color = '#99182431'
  static placeholder_color = '#99182431'


}