export default class Constants {
  static readonly LOGIN_KEYS = 'loginKeys'
  static readonly LOGIN_TOKEN = "loginToken"
  static readonly LOGIN_USER_INFO = "loginUser"

  static readonly USER_NAME = "user_name"
  static readonly CRYPTO_PASSWORD = "crypt_password"
  static readonly IS_SHOW_FACE = "is_show_face"
  static readonly IS_SHOW_FINGERPRINT = "is_show_fingerprint"

  static readonly IS_HIDDEN_BALANCE = "is_hidden_balance"

  static readonly MILLISECONDS_TO_SECONDS = 1

  static readonly INPUT_ACCOUNT_LENGTH = 20
  static readonly INPUT_PASSWORD_LENGTH = 32
  static readonly BUTTON_WIDTH = '90%'

  static readonly LOGIN_METHODS_SPACE: number = 44
}