export default class Dimensions {

  static readonly FULL_PARENT = '100%'
  static readonly title_text_size = '24vp'
  static readonly topnav_text_size = '18vp'
  static readonly normal_text_size = '16vp'
  static readonly small_text_size = '14vp'
  static readonly little_text_size = '12vp'

  static readonly content_text_size = '14vp'
  static readonly content_line_size = '18vp'

  static readonly inputBorderRadius = '24vp'

  static readonly inputHeight = '48vp'
  static readonly input_padding_top = '4vp'
  static readonly input_padding_left = '12vp'
  static readonly input_margin_top = '12vp'

  static readonly line_height = '1vp'

}